@MayTheFourth.Backend_HostAddress = http://localhost:5102

GET {{MayTheFourth.Backend_HostAddress}}/film/
Accept: application/json

###

GET {{MayTheFourth.Backend_HostAddress}}/film/1
Accept: application/json

###

GET {{MayTheFourth.Backend_HostAddress}}/v1/characters/
Accept: application/json

###

GET {{MayTheFourth.Backend_HostAddress}}/v1/characters/1
Accept: application/json

###
